# Copyright (c) 2026, Arkan Labs and contributors
# auracrm/industry/preset_data.py
# 8 built-in industry presets for AuraCRM Industry Preset DocType

INDUSTRY_PRESETS = [
    # ── 1. Real Estate ────────────────────────────────────────
    {
        "preset_name": "Real Estate",
        "preset_code": "real_estate",
        "term_lead": "Prospect",
        "term_deal": "Listing",
        "term_product": "Property",
        "term_company": "Agency",
        "term_agent": "Agent",
        "enable_property_inventory": 1,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 0,
        "enable_physical_location": 1,
        "enable_compliance_fields": 1,
        "enable_project_milestones": 0,
        "enable_rental_management": 1,
        "qualification_fields": [
            {"fieldname": "property_budget", "label": "Budget Range", "type": "Currency"},
            {"fieldname": "property_type_interest", "label": "Property Type Interest", "type": "Select",
             "options": "Apartment\nVilla\nTownhouse\nLand\nCommercial"},
            {"fieldname": "bedrooms_required", "label": "Bedrooms Required", "type": "Int"},
            {"fieldname": "preferred_location", "label": "Preferred Location", "type": "Data"},
        ],
        "default_score_rules": [
            {"rule_name": "Budget Qualified", "field": "property_budget", "operator": ">", "value": "0", "points": 20},
            {"rule_name": "Location Specified", "field": "preferred_location", "operator": "is_set", "value": "", "points": 15},
        ],
        "default_sla_policies": [
            {"name": "Hot Lead Response", "priority": "High", "response_hours": 1, "resolution_hours": 24},
            {"name": "Viewing Follow-up", "priority": "Medium", "response_hours": 4, "resolution_hours": 72},
        ],
        "default_osint_segments": ["Property Buyers", "Investors", "Tenants", "Commercial Lessees"],
        "caps_capability_templates": [
            {"code": "re_listing_mgmt", "name": "Listing Management", "category": "Real Estate"},
            {"code": "re_virtual_tour", "name": "Virtual Tour", "category": "Real Estate"},
            {"code": "re_valuation", "name": "Property Valuation", "category": "Real Estate"},
        ],
        "default_kpis": [
            {"name": "Listings Active", "metric": "count", "doctype": "Lead", "filter": {"status": "Open"}},
            {"name": "Avg Days to Close", "metric": "avg_days", "doctype": "Lead", "date_field": "creation"},
        ],
        "content_topic_suggestions": ["Market Insights", "Neighborhood Guide", "Investment Tips", "Home Staging"],
    },

    # ── 2. Hospitality ────────────────────────────────────────
    {
        "preset_name": "Hospitality",
        "preset_code": "hospitality",
        "term_lead": "Guest",
        "term_deal": "Reservation",
        "term_product": "Room / Package",
        "term_company": "Hotel",
        "term_agent": "Concierge",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 0,
        "enable_physical_location": 1,
        "enable_compliance_fields": 0,
        "enable_project_milestones": 0,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "check_in_date", "label": "Check-in Date", "type": "Date"},
            {"fieldname": "check_out_date", "label": "Check-out Date", "type": "Date"},
            {"fieldname": "guests_count", "label": "Number of Guests", "type": "Int"},
            {"fieldname": "room_preference", "label": "Room Preference", "type": "Select",
             "options": "Standard\nDeluxe\nSuite\nPenthouse"},
        ],
        "default_score_rules": [
            {"rule_name": "Repeat Guest", "field": "repeat_visit", "operator": "==", "value": "1", "points": 25},
            {"rule_name": "Group Booking", "field": "guests_count", "operator": ">", "value": "4", "points": 15},
        ],
        "default_sla_policies": [
            {"name": "VIP Guest", "priority": "High", "response_hours": 0.5, "resolution_hours": 4},
            {"name": "General Inquiry", "priority": "Medium", "response_hours": 2, "resolution_hours": 24},
        ],
        "default_osint_segments": ["Business Travelers", "Leisure Tourists", "Event Planners", "Travel Agencies"],
        "caps_capability_templates": [
            {"code": "hosp_booking_mgmt", "name": "Booking Management", "category": "Hospitality"},
            {"code": "hosp_guest_profile", "name": "Guest Profiling", "category": "Hospitality"},
        ],
        "default_kpis": [
            {"name": "Occupancy Rate", "metric": "percentage", "target": 85},
            {"name": "Avg Revenue/Guest", "metric": "avg_amount", "doctype": "Lead"},
        ],
        "content_topic_suggestions": ["Travel Tips", "Local Attractions", "Seasonal Packages", "Guest Stories"],
    },

    # ── 3. Healthcare ─────────────────────────────────────────
    {
        "preset_name": "Healthcare",
        "preset_code": "healthcare",
        "term_lead": "Patient",
        "term_deal": "Case",
        "term_product": "Service",
        "term_company": "Clinic",
        "term_agent": "Care Coordinator",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 0,
        "enable_physical_location": 1,
        "enable_compliance_fields": 1,
        "enable_project_milestones": 0,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "specialty_needed", "label": "Specialty Needed", "type": "Data"},
            {"fieldname": "insurance_provider", "label": "Insurance Provider", "type": "Data"},
            {"fieldname": "urgency_level", "label": "Urgency Level", "type": "Select",
             "options": "Routine\nUrgent\nEmergency"},
        ],
        "default_score_rules": [
            {"rule_name": "Insurance Verified", "field": "insurance_provider", "operator": "is_set", "value": "", "points": 20},
            {"rule_name": "Urgent Case", "field": "urgency_level", "operator": "==", "value": "Urgent", "points": 30},
        ],
        "default_sla_policies": [
            {"name": "Emergency", "priority": "Critical", "response_hours": 0.25, "resolution_hours": 1},
            {"name": "Routine Appointment", "priority": "Low", "response_hours": 24, "resolution_hours": 168},
        ],
        "default_osint_segments": ["Patients", "Referring Physicians", "Insurance Companies"],
        "caps_capability_templates": [
            {"code": "hc_appointment", "name": "Appointment Scheduling", "category": "Healthcare"},
            {"code": "hc_compliance", "name": "HIPAA Compliance", "category": "Healthcare"},
            {"code": "hc_patient_portal", "name": "Patient Portal", "category": "Healthcare"},
        ],
        "default_kpis": [
            {"name": "Patient Satisfaction", "metric": "score", "target": 4.5},
            {"name": "Avg Wait Time", "metric": "avg_minutes", "target": 15},
        ],
        "content_topic_suggestions": ["Health Tips", "Wellness Programs", "Preventive Care", "Patient Education"],
    },

    # ── 4. Legal ──────────────────────────────────────────────
    {
        "preset_name": "Legal",
        "preset_code": "legal",
        "term_lead": "Client",
        "term_deal": "Matter",
        "term_product": "Legal Service",
        "term_company": "Firm",
        "term_agent": "Attorney",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 0,
        "enable_physical_location": 0,
        "enable_compliance_fields": 1,
        "enable_project_milestones": 1,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "practice_area", "label": "Practice Area", "type": "Select",
             "options": "Corporate\nLitigation\nFamily\nReal Estate\nIP\nCriminal\nTax"},
            {"fieldname": "case_value", "label": "Estimated Case Value", "type": "Currency"},
            {"fieldname": "retainer_status", "label": "Retainer Status", "type": "Select",
             "options": "None\nPending\nActive"},
        ],
        "default_score_rules": [
            {"rule_name": "High-Value Matter", "field": "case_value", "operator": ">", "value": "50000", "points": 25},
            {"rule_name": "Retainer Active", "field": "retainer_status", "operator": "==", "value": "Active", "points": 30},
        ],
        "default_sla_policies": [
            {"name": "Urgent Matter", "priority": "High", "response_hours": 2, "resolution_hours": 48},
            {"name": "Consultation Request", "priority": "Medium", "response_hours": 8, "resolution_hours": 120},
        ],
        "default_osint_segments": ["Corporate Clients", "Individual Clients", "Referral Partners"],
        "caps_capability_templates": [
            {"code": "legal_matter_mgmt", "name": "Matter Management", "category": "Legal"},
            {"code": "legal_billing", "name": "Legal Billing", "category": "Legal"},
            {"code": "legal_compliance", "name": "Compliance Tracking", "category": "Legal"},
        ],
        "default_kpis": [
            {"name": "Billable Hours", "metric": "sum_hours", "target": 160},
            {"name": "Matter Win Rate", "metric": "percentage", "target": 70},
        ],
        "content_topic_suggestions": ["Legal Updates", "Case Studies", "Regulatory Changes", "Industry Analysis"],
    },

    # ── 5. SaaS ───────────────────────────────────────────────
    {
        "preset_name": "SaaS",
        "preset_code": "saas",
        "term_lead": "Trial User",
        "term_deal": "Subscription",
        "term_product": "Plan",
        "term_company": "Organization",
        "term_agent": "Account Executive",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 0,
        "enable_subscription_products": 1,
        "enable_physical_location": 0,
        "enable_compliance_fields": 0,
        "enable_project_milestones": 0,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "company_size", "label": "Company Size", "type": "Select",
             "options": "1-10\n11-50\n51-200\n201-1000\n1000+"},
            {"fieldname": "current_solution", "label": "Current Solution", "type": "Data"},
            {"fieldname": "annual_budget", "label": "Annual Budget", "type": "Currency"},
            {"fieldname": "decision_timeline", "label": "Decision Timeline", "type": "Select",
             "options": "Immediate\n1-3 Months\n3-6 Months\n6+ Months"},
        ],
        "default_score_rules": [
            {"rule_name": "Enterprise Size", "field": "company_size", "operator": "in", "value": "201-1000,1000+", "points": 25},
            {"rule_name": "Immediate Decision", "field": "decision_timeline", "operator": "==", "value": "Immediate", "points": 20},
            {"rule_name": "Budget Qualified", "field": "annual_budget", "operator": ">", "value": "10000", "points": 15},
        ],
        "default_sla_policies": [
            {"name": "Enterprise Lead", "priority": "High", "response_hours": 1, "resolution_hours": 24},
            {"name": "SMB Lead", "priority": "Medium", "response_hours": 4, "resolution_hours": 72},
            {"name": "Free Trial", "priority": "Low", "response_hours": 24, "resolution_hours": 168},
        ],
        "default_osint_segments": ["Enterprise Prospects", "SMB Prospects", "Churned Users", "Trial Users"],
        "caps_capability_templates": [
            {"code": "saas_onboarding", "name": "Automated Onboarding", "category": "SaaS"},
            {"code": "saas_usage_analytics", "name": "Usage Analytics", "category": "SaaS"},
            {"code": "saas_churn_predict", "name": "Churn Prediction", "category": "SaaS"},
        ],
        "default_kpis": [
            {"name": "MRR", "metric": "sum_amount", "doctype": "Lead"},
            {"name": "Churn Rate", "metric": "percentage", "target": 5},
            {"name": "Trial-to-Paid", "metric": "conversion_rate", "target": 15},
        ],
        "content_topic_suggestions": ["Product Updates", "Use Cases", "Integration Guides", "ROI Calculators"],
    },

    # ── 6. Education ──────────────────────────────────────────
    {
        "preset_name": "Education",
        "preset_code": "education",
        "term_lead": "Applicant",
        "term_deal": "Enrollment",
        "term_product": "Program",
        "term_company": "Institution",
        "term_agent": "Admissions Counselor",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 1,
        "enable_physical_location": 1,
        "enable_compliance_fields": 1,
        "enable_project_milestones": 1,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "program_interest", "label": "Program of Interest", "type": "Data"},
            {"fieldname": "education_level", "label": "Education Level", "type": "Select",
             "options": "High School\nBachelor\nMaster\nDoctorate\nCertificate"},
            {"fieldname": "start_semester", "label": "Preferred Start Semester", "type": "Select",
             "options": "Fall\nSpring\nSummer"},
        ],
        "default_score_rules": [
            {"rule_name": "Program Match", "field": "program_interest", "operator": "is_set", "value": "", "points": 20},
            {"rule_name": "Immediate Start", "field": "start_semester", "operator": "is_set", "value": "", "points": 10},
        ],
        "default_sla_policies": [
            {"name": "Scholarship Inquiry", "priority": "High", "response_hours": 4, "resolution_hours": 48},
            {"name": "General Admission", "priority": "Medium", "response_hours": 24, "resolution_hours": 120},
        ],
        "default_osint_segments": ["Prospective Students", "Parents", "Transfer Students", "International Students"],
        "caps_capability_templates": [
            {"code": "edu_admission_mgmt", "name": "Admission Management", "category": "Education"},
            {"code": "edu_student_portal", "name": "Student Portal", "category": "Education"},
        ],
        "default_kpis": [
            {"name": "Enrollment Rate", "metric": "conversion_rate", "target": 30},
            {"name": "Avg Application Score", "metric": "avg_score", "target": 75},
        ],
        "content_topic_suggestions": ["Campus Life", "Program Highlights", "Alumni Stories", "Career Outcomes"],
    },

    # ── 7. Automotive ─────────────────────────────────────────
    {
        "preset_name": "Automotive",
        "preset_code": "automotive",
        "term_lead": "Buyer",
        "term_deal": "Sale",
        "term_product": "Vehicle",
        "term_company": "Dealership",
        "term_agent": "Sales Consultant",
        "enable_property_inventory": 1,
        "enable_appointment_booking": 1,
        "enable_subscription_products": 0,
        "enable_physical_location": 1,
        "enable_compliance_fields": 1,
        "enable_project_milestones": 0,
        "enable_rental_management": 1,
        "qualification_fields": [
            {"fieldname": "vehicle_type", "label": "Vehicle Type", "type": "Select",
             "options": "Sedan\nSUV\nTruck\nCoupe\nConvertible\nVan\nElectric"},
            {"fieldname": "budget_range", "label": "Budget Range", "type": "Currency"},
            {"fieldname": "trade_in", "label": "Has Trade-In", "type": "Check"},
            {"fieldname": "financing_needed", "label": "Financing Needed", "type": "Check"},
        ],
        "default_score_rules": [
            {"rule_name": "Ready to Buy", "field": "decision_timeline", "operator": "==", "value": "Immediate", "points": 30},
            {"rule_name": "Trade-In Available", "field": "trade_in", "operator": "==", "value": "1", "points": 15},
            {"rule_name": "Financing Pre-Approved", "field": "financing_needed", "operator": "==", "value": "0", "points": 10},
        ],
        "default_sla_policies": [
            {"name": "Showroom Visit", "priority": "High", "response_hours": 0.5, "resolution_hours": 4},
            {"name": "Online Inquiry", "priority": "Medium", "response_hours": 2, "resolution_hours": 24},
        ],
        "default_osint_segments": ["New Buyers", "Pre-Owned Buyers", "Fleet Buyers", "Lease Renewals"],
        "caps_capability_templates": [
            {"code": "auto_inventory", "name": "Vehicle Inventory", "category": "Automotive"},
            {"code": "auto_test_drive", "name": "Test Drive Scheduling", "category": "Automotive"},
            {"code": "auto_financing", "name": "Financing Calculator", "category": "Automotive"},
        ],
        "default_kpis": [
            {"name": "Units Sold", "metric": "count", "target": 50},
            {"name": "Avg Deal Value", "metric": "avg_amount", "doctype": "Lead"},
            {"name": "Test Drive Conversion", "metric": "conversion_rate", "target": 25},
        ],
        "content_topic_suggestions": ["New Models", "Financing Tips", "Maintenance Guides", "Comparison Reviews"],
    },

    # ── 8. E-Commerce ─────────────────────────────────────────
    {
        "preset_name": "E-Commerce",
        "preset_code": "ecommerce",
        "term_lead": "Shopper",
        "term_deal": "Order",
        "term_product": "Product",
        "term_company": "Store",
        "term_agent": "Customer Success",
        "enable_property_inventory": 0,
        "enable_appointment_booking": 0,
        "enable_subscription_products": 1,
        "enable_physical_location": 0,
        "enable_compliance_fields": 0,
        "enable_project_milestones": 0,
        "enable_rental_management": 0,
        "qualification_fields": [
            {"fieldname": "cart_value", "label": "Cart Value", "type": "Currency"},
            {"fieldname": "product_category", "label": "Product Category Interest", "type": "Data"},
            {"fieldname": "purchase_frequency", "label": "Purchase Frequency", "type": "Select",
             "options": "One-Time\nMonthly\nWeekly"},
        ],
        "default_score_rules": [
            {"rule_name": "High Cart Value", "field": "cart_value", "operator": ">", "value": "200", "points": 20},
            {"rule_name": "Repeat Buyer", "field": "purchase_frequency", "operator": "in", "value": "Monthly,Weekly", "points": 25},
        ],
        "default_sla_policies": [
            {"name": "Abandoned Cart", "priority": "High", "response_hours": 1, "resolution_hours": 12},
            {"name": "Support Ticket", "priority": "Medium", "response_hours": 4, "resolution_hours": 48},
        ],
        "default_osint_segments": ["Active Shoppers", "Cart Abandoners", "Wishlist Users", "VIP Customers"],
        "caps_capability_templates": [
            {"code": "ecom_cart_recovery", "name": "Cart Recovery", "category": "E-Commerce"},
            {"code": "ecom_recommendation", "name": "Product Recommendations", "category": "E-Commerce"},
            {"code": "ecom_loyalty", "name": "Loyalty Program", "category": "E-Commerce"},
        ],
        "default_kpis": [
            {"name": "Conversion Rate", "metric": "percentage", "target": 3},
            {"name": "Avg Order Value", "metric": "avg_amount", "target": 120},
            {"name": "Cart Recovery Rate", "metric": "percentage", "target": 15},
        ],
        "content_topic_suggestions": ["Product Launches", "Seasonal Sales", "Style Guides", "Customer Reviews"],
    },
]
